### ISSUE TITLE
RMF Items Missing From JEI/REI/EMI/Creative Inv.

### ISSUE THREAD

**Issue by ezrazazeldev** [regfunkid/More-Foods-Datapack#23]
As the title says, all RMF items are completely missing from the creative inventory and any "xyz enough items" mods I've tried.

**Comment by regfunkid** [comment]
Hey, thanks for submitting a bug report!
Unfortunately, due to the way the project works, any mod that allows for finding items in a "xyz enough items" mod format will not be compatible with Reg's More Foods.

Simply put, Reg's More Foods doesn't actually *add* any new items to the game, but rather makes use of various tools like `custom_model_data` and Components.

As soon as Mojang release some form of Data Driven Items, I will have a fix for this!

(If you'd still like to make use of whatever item-finder mod you have installed, try searching up "firework stars", "honey bottles", "mushroom stew", "poisonous potatoes", or "tropical fish" in your menu. The custom foods will be listed under them.)
