### ISSUE TITLE
All items use the Firework Star graphic instead of the custom ones

### ISSUE THREAD

**Issue by mr-briggs** [regfunkid/More-Foods-Datapack#27]
It's rather odd, but after installing the 1.1.2+1.21+fabric version of the mod through ATLauncher (using the Modrinth release), the items are available but use only the Firework Star graphic, as seen below:

![2024-09-17_00 05 42](https://github.com/user-attachments/assets/24f25f9f-96a9-4ec2-a459-32843a0e368c)

I've tried re-installing, installing the 1.1.1 version of the mod, etc, but no luck sadly. This occurs both on servers and in singleplayer. I haven't tried the data pack version yet, but wasn't sure how exactly to do so when using an ATLauncher-managed instance.

Any ideas about what might be going wrong? Have I perhaps just missed some obvious setup step? 🤔

**Comment by regfunkid** [comment]
That's very strange! If you're able to, try checking your profile in your launcher to see if the ATLauncher you're using included the "assets" folder in the .jar for the 1.1.2 version-- the "assets" folder is where all the textures are located, so if that's missing then none of your textures would load.
Otherwise, try checking the console to see if anything pops up.

In the meantime, I'm going to look into this ATLauncher you're using since Reg's More Foods isn't available on there. Maybe however they got it from Modrinth is what broke it?

In the mean-er time, you can always manually install the resource pack by downloading the data pack version from Modrinth and taking the resource pack from that.

**Comment by regfunkid** [comment]
I haven't been able to find anything thus far, unfortunately. I'm unsure how this bug happened or how to really fix it from my end (since it seems unique to the ATLauncher?), but if anyone can give me a hand that would be great. From what it looks like, manually downloading the Resource Pack from Modrinth will fix this.
For now though, I'm making this as "fixed" since it doesn't happen for any other version of the project that I know of.
