### ISSUE TITLE
More Versions

### ISSUE THREAD

**Issue by niki142009** [regfunkid/More-Foods-Datapack#31]
Alo, can you pls add more versions like 1.20.1, is this possible?

**Comment by regfunkid** [comment]
Hi! Unfortunately, Reg's More Foods only works from version 1.20.5 and up. This is because it utilizes the new Component system that replaced NBT data--to put it simply, it won't work in older versions.

Sorry if this is an inconvenience to you. Please let me know if you have any other questions though!
