### ISSUE TITLE
Bug Report Rabbits foot replaced with Bucket of Milk

### ISSUE THREAD

**Issue by Trico-Everfire** [regfunkid/More-Foods-Datapack#33]
### What happened?
The rabbits foot is just flat out replaced with a bucket of milk. In both texture and translated name.

### How to replicate/reproduce:
Get a rabbits foot.

### What version did you find the issue on?
1.21.3

### If you have a screenshot or video of the issue, please link it here.
![image](https://github.com/user-attachments/assets/fb9dc180-1281-4af2-b566-319ea5439a84)
![image](https://github.com/user-attachments/assets/abb8ebb4-8dd2-4f27-95bf-5c08791a5159)

**Comment by Trico-Everfire** [comment]
The way everything is set up by itself is really weird. Why are they rabbits foot? chocolate milk is a firework star like all other foods. To be honest. Using obtainable items for anything is an odd choice I'd personally recommend the command block/structure block items as they cannot be placed in survival, nor obtained. Also overriding base items with data/resource pack textures is ill adviced and recommended to use custom data models.

**Comment by regfunkid** [comment]
This is actually intentional behavior. Due to the way I had to code this to add custom crafting ingredients to the game, a couple vanilla items had to be essentially replaced. You can exploit this a fair bit if you know which items have been replaced, but in the case of Rabbit's Feet, it still works the same way as a normal version. Killing Rabbits will still drop the regular textured item.

Fixing all Rabbit's Foot items from containers is quite annoying since I don't know if any other datapacks have messed with it, and making a function to update them automatically might break other packs. I'll see if I can fix this in the future but for now it's low priority.

(I also don't want to use admin items like Command Blocks, even if they can't be placed in Survival Mode, I prefer to not give players those kinds of items, despite them not being able to use them)

**Comment by Trico-Everfire** [comment]
>  it still works the same way as a normal version. Killing Rabbits will still drop the regular textured item.

It doesn't. Well, at least, it doesn't for the rabbits foot given to you by cats that sleep on you. If this is a separate issue reopen it with a renamed title.

**Comment by regfunkid** [comment]
Oh. Wow, I actually missed that with the cat gifting. Thank you for pointing that out.
You know what's funny? There was a similar issue with Phantoms not dropping the correct item, but NOBODY has told me presumably because nobody plays with phantoms enabled.

Anywho, it's fixed. Thanks! Any Rabbit's Foot items still inside chests won't be updated but killing rabbits and getting cat gifts should be fine now.

**Comment by Trico-Everfire** [comment]
It is kinda funny, On my server we do play with phantoms. So we would've noticed if that was a bug.
